// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ-S9r7HcbuogniDX7IO4X67N1o9AHAGg',
    appId: '1:259279884876:web:776fca0be4a7b7f997dae9',
    messagingSenderId: '259279884876',
    projectId: 'miiltoo',
    authDomain: 'miiltoo.firebaseapp.com',
    storageBucket: 'miiltoo.firebasestorage.app',
    measurementId: 'G-ZQDESD02WV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFJ58tk1ISIKQPFjVWCxcu8Um6W-9m7fw',
    appId: '1:259279884876:android:f55d70e7661198f997dae9',
    messagingSenderId: '259279884876',
    projectId: 'miiltoo',
    storageBucket: 'miiltoo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVO2nRNG1z0h7EoIUVmjnh7RVfGyVfq7M',
    appId: '1:259279884876:ios:f9ee0e74370189e297dae9',
    messagingSenderId: '259279884876',
    projectId: 'miiltoo',
    storageBucket: 'miiltoo.firebasestorage.app',
    iosBundleId: 'com.example.miiltoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVO2nRNG1z0h7EoIUVmjnh7RVfGyVfq7M',
    appId: '1:259279884876:ios:f9ee0e74370189e297dae9',
    messagingSenderId: '259279884876',
    projectId: 'miiltoo',
    storageBucket: 'miiltoo.firebasestorage.app',
    iosBundleId: 'com.example.miiltoo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ-S9r7HcbuogniDX7IO4X67N1o9AHAGg',
    appId: '1:259279884876:web:7154ff467342573897dae9',
    messagingSenderId: '259279884876',
    projectId: 'miiltoo',
    authDomain: 'miiltoo.firebaseapp.com',
    storageBucket: 'miiltoo.firebasestorage.app',
    measurementId: 'G-FMWEDE6VER',
  );
}
